// The brand guide: one self-contained HTML page generated from the same files agents read
// (brand/brand-system.json and brand/tokens). People read the page; agents read the JSON embedded in it,
// or the source files. It is never edited by hand, so the two layers cannot drift apart.
import path from 'node:path';
import { readData, writeAtomic, hashValue } from './core.mjs';
import { brandContext } from './brand.mjs';
import { loadTokens, colorHex, buildCSSText, resolve } from './tokens.mjs';

const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const label = (k) => k.replace(/_/g, ' ');
const show = (v) => (typeof v === 'string' ? esc(v) : Array.isArray(v) && v.every((x) => typeof x === 'string') ? v.map(esc).join(', ') : `<code>${esc(JSON.stringify(v))}</code>`);

export function buildGuide(ws, { out } = {}) {
  const bs = readData(path.join(ws, 'brand', 'brand-system.json'));
  const ctx = brandContext(ws);
  const tokens = loadTokens(ws);
  const { css } = buildCSSText(tokens);
  const sourceOf = (sec, k) => (bs.sections?.[sec]?.[k]?.sources ?? []).map((s) => s.ref).filter(Boolean);

  // the brand system's own section order (business truth first), not the alphabetical order of the context
  const order = Object.keys(bs.sections ?? {}).filter((sec) => ctx.facts[sec]);
  const sections = order.map((sec) => [sec, ctx.facts[sec]]).map(([sec, fields]) => {
    const rows = Object.entries(fields).map(([k, f]) => {
      const locked = f && typeof f === 'object' && f.locked === true;
      const value = locked ? f.value : f;
      const refs = sourceOf(sec, k);
      return `<tr><th>${esc(label(k))}${locked ? ' <span class="tag">locked</span>' : ''}</th><td>${show(value)}${refs.length ? `<div class="src">${refs.map(esc).join(' · ')}</div>` : ''}</td></tr>`;
    });
    return `<section><h2>${esc(label(sec))}</h2><table>${rows.join('')}</table></section>`;
  });

  const colours = Object.keys(tokens).filter((n) => tokens[n].type === 'color').sort().map((n) => {
    const hex = colorHex(resolve(tokens, n));
    return hex ? `<figure><div class="chip" style="background:${esc(hex)}"></div><figcaption>${esc(n)}<br>${esc(hex)}</figcaption></figure>` : '';
  });
  const families = Object.keys(tokens).filter((n) => tokens[n].type === 'fontFamily').sort().map((n) => {
    const v = resolve(tokens, n);
    const stack = (Array.isArray(v) ? v : [v]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
    return `<p style="font-family:${esc(stack)}"><span class="name">${esc(n)}</span> The quick brown fox jumps over the lazy dog 0123456789</p>`;
  });

  const open = ctx.not_facts.length ? `<section><h2>Not settled</h2><p class="note">These are not brand fact yet. Ask the owner before relying on them.</p><ul>${ctx.not_facts.filter((n) => !/\(UNKNOWN\)$/.test(n)).map((n) => `<li>${esc(n)}</li>`).join('')}</ul></section>` : '';
  const machine = { context: ctx, tokens_hash: hashValue(tokens).slice(0, 12) };
  const name = ctx.brand ?? bs.metadata?.brand_id ?? 'Brand';
  const html = `<!doctype html>
<!-- GENERATED by cstack brand guide from brand/brand-system.json and brand/tokens. Do not edit; rebuild it. context ${ctx.hash} tokens ${machine.tokens_hash} -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(name)} brand guide</title>
<style>
${css}
body{margin:0 auto;max-width:56rem;padding:2rem 1rem;font:16px/1.5 system-ui,sans-serif;color:#111;background:#fff}
h1{font-size:2rem;margin:0 0 .25rem}h2{font-size:1rem;text-transform:uppercase;letter-spacing:.06em;border-top:1px solid #ccc;padding-top:1rem;margin-top:2rem}
table{border-collapse:collapse;width:100%}th,td{text-align:left;vertical-align:top;padding:.4rem .5rem .4rem 0}th{width:14rem;font-weight:600}
.src,.note,figcaption,.meta{font-size:.8rem;color:#555}.tag{font-size:.7rem;border:1px solid currentColor;padding:0 .3rem;font-weight:400}
.chips{display:flex;flex-wrap:wrap;gap:1rem}figure{margin:0;width:7rem}.chip{height:4rem;border:1px solid #ccc}.name{display:block;font:.8rem system-ui,sans-serif;color:#555}
code{font-size:.85em;word-break:break-word}
</style></head><body>
<h1>${esc(name)}</h1>
<p class="meta">Brand guide generated from the brand files${bs.metadata?.updated ? `, brand system updated ${esc(bs.metadata.updated)}` : ''}. Only approved fields appear as fact; each shows where it came from.</p>
${colours.filter(Boolean).length ? `<section><h2>Color tokens</h2><div class="chips">${colours.join('')}</div></section>` : ''}
${families.length ? `<section><h2>Type tokens</h2>${families.join('')}</section>` : ''}
${sections.join('\n')}
${open}
<script type="application/json" id="brand-context">${JSON.stringify(machine).replace(/</g, '\\u003c')}</script>
</body></html>
`;
  const p = out ?? path.join(ws, 'brand', 'generated', 'guide.html');
  writeAtomic(p, html);
  return { file: p, sections: sections.length, colours: colours.filter(Boolean).length, hash: ctx.hash };
}
