// Design tokens (W3C DTCG 2025.10 format): the lowest, most reliable level to encode a brand decision.
// "Do not ask the model to remember the brand; make the brand executable." Tokens live in
// <ws>/brand/tokens/*.tokens.json, are checked here, compiled to CSS custom properties, and used to
// lint built pages for raw values (a deterministic check never goes to an LLM judge).
import fs from 'node:fs';
import path from 'node:path';
import { exists, readJSON, writeAtomic, hashValue } from './core.mjs';

const TYPES = new Set(['color', 'dimension', 'fontFamily', 'fontWeight', 'duration', 'cubicBezier', 'number', 'strokeStyle', 'border', 'transition', 'shadow', 'gradient', 'typography']);
const ALIAS = /^\{([^}]+)\}$/;

export function tokenFiles(ws) {
  const dir = path.join(ws, 'brand', 'tokens');
  return exists(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.tokens.json')).sort().map((f) => path.join(dir, f)) : [];
}

// Flatten groups into {"color.brand.primary": {type, value, description, file}}; $type inherits from groups.
export function flatten(tree, file, prefix = [], inheritedType, out = {}) {
  for (const [k, v] of Object.entries(tree)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) {
      out[[...prefix, k].join('.')] = { type: v.$type ?? inheritedType ?? null, value: v.$value, description: v.$description, deprecated: v.$deprecated, file };
    } else if (v && typeof v === 'object') flatten(v, file, [...prefix, k], v.$type ?? inheritedType, out);
  }
  return out;
}

export function loadTokens(ws) {
  const all = {};
  for (const f of tokenFiles(ws)) Object.assign(all, flatten(readJSON(f), path.basename(f)));
  return all;
}

function resolve(tokens, name, seen = new Set()) {
  const t = tokens[name];
  if (!t) throw new Error(`alias to missing token {${name}}`);
  if (typeof t.value === 'string' && ALIAS.test(t.value)) {
    const target = t.value.match(ALIAS)[1];
    if (seen.has(target)) throw new Error(`alias cycle at {${target}}`);
    seen.add(name);
    return resolve(tokens, target, seen);
  }
  return t.value;
}

// DTCG color values may be objects ({colorSpace, components, hex}) or legacy hex strings.
export function colorHex(v) {
  if (typeof v === 'string') return /^#[0-9a-f]{3,8}$/i.test(v) ? v.toLowerCase() : null;
  if (v?.hex) return String(v.hex).toLowerCase();
  if (v?.colorSpace === 'srgb' && Array.isArray(v.components)) return '#' + v.components.map((c) => Math.round(c * 255).toString(16).padStart(2, '0')).join('');
  return null;
}

export function checkTokens(ws) {
  const problems = [];
  const tokens = loadTokens(ws);
  for (const [name, t] of Object.entries(tokens)) {
    if (!t.type) problems.push(`${name}: no $type (set it on the token or a parent group)`);
    else if (!TYPES.has(t.type)) problems.push(`${name}: unknown $type "${t.type}"`);
    try {
      const v = resolve(tokens, name);
      if (t.type === 'color' && !colorHex(v)) problems.push(`${name}: color value is not sRGB hex or {colorSpace:"srgb",components}`);
    } catch (e) {
      problems.push(`${name}: ${e.message}`);
    }
  }
  return { count: Object.keys(tokens).length, problems, ok: problems.length === 0 };
}

const cssValue = (t, v) => {
  if (t.type === 'color') return colorHex(v);
  if (t.type === 'dimension' || t.type === 'duration') return typeof v === 'object' ? `${v.value}${v.unit}` : v;
  if (t.type === 'fontFamily') return (Array.isArray(v) ? v : [v]).map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
  if (t.type === 'cubicBezier') return `cubic-bezier(${v.join(', ')})`;
  if (typeof v === 'object') return null; // composite tokens (typography, shadow ...) are emitted by a later compiler
  return String(v);
};

export function buildCSS(ws, { out } = {}) {
  const tokens = loadTokens(ws);
  const lines = [];
  for (const name of Object.keys(tokens).sort()) {
    const t = tokens[name];
    const v = cssValue(t, resolve(tokens, name));
    if (v != null) lines.push(`  --${name.replace(/\./g, '-')}: ${v};`);
  }
  const css = `/* GENERATED by cstack tokens build from brand/tokens/*.tokens.json. Do not edit. hash:${hashValue(tokens).slice(0, 12)} */\n:root {\n${lines.join('\n')}\n}\n`;
  const p = out ?? path.join(ws, 'brand', 'generated', 'tokens.css');
  writeAtomic(p, css);
  return { file: p, count: lines.length };
}

// #rgb, #rgba, #rrggbb, #rrggbbaa -> '#rrggbb' (alpha dropped: a translucent brand colour is still that colour)
export function hexRGB(hex) {
  let h = String(hex).trim().toLowerCase().replace(/^#/, '');
  if (!/^([0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/.test(h)) return null;
  if (h.length <= 4) h = [...h].map((c) => c + c).join('');
  return '#' + h.slice(0, 6);
}

// rgb(255 0 0) / rgba(255, 0, 0, .5) / rgb(100% 0% 0%) -> '#rrggbb'; null when not plain numbers
function rgbFn(args) {
  const parts = args.split(/[\s,/]+/).filter(Boolean).slice(0, 3);
  if (parts.length < 3) return null;
  const ch = parts.map((x) => (/^\d+(\.\d+)?%$/.test(x) ? (parseFloat(x) / 100) * 255 : /^\d+(\.\d+)?$/.test(x) ? Number(x) : NaN));
  if (ch.some((c) => !Number.isFinite(c) || c > 255)) return null;
  return '#' + ch.map((c) => Math.round(c).toString(16).padStart(2, '0')).join('');
}

const RAW_COLOR = /#(?:[0-9a-f]{8}|[0-9a-f]{6}|[0-9a-f]{4}|[0-9a-f]{3})\b|\b(rgba?|hsla?|hwb|lab|lch|oklab|oklch|color)\(([^()]*)\)/gi;

// Raw-value lint: colours in CSS/HTML that are not a brand token value (hex with or without alpha, rgb() and the
// other colour functions). Exceptions must be explicit (--allow, compared the same way).
export function lintRaw(ws, files, { allow = [] } = {}) {
  const tokens = loadTokens(ws);
  const palette = new Set();
  const literal = new Set();
  for (const a of allow) {
    const h = hexRGB(a);
    if (h) palette.add(h);
    else literal.add(String(a).replace(/\s+/g, '').toLowerCase());
  }
  for (const name of Object.keys(tokens)) if (tokens[name].type === 'color') palette.add(hexRGB(colorHex(resolve(tokens, name))));
  const findings = [];
  for (const f of files) {
    const text = fs.readFileSync(f, 'utf8');
    text.split('\n').forEach((line, i) => {
      for (const m of line.matchAll(RAW_COLOR)) {
        if (m[2]?.includes('var(') || literal.has(m[0].replace(/\s+/g, '').toLowerCase())) continue;
        const fn = m[1]?.toLowerCase();
        const hex = fn ? (fn.startsWith('rgb') ? rgbFn(m[2]) : null) : hexRGB(m[0]);
        if (hex && palette.has(hex)) continue;
        const detail = fn && !hex ? `raw ${fn}() colour cannot be matched to a token (use a token or record an exception)` : 'raw color not in brand tokens (use a token or record an exception)';
        findings.push({ file: f, line: i + 1, value: m[0], detail });
      }
    });
  }
  return { findings, ok: findings.length === 0, palette_size: palette.size };
}
